apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mongo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-mongo
  template:
    metadata:
      labels:
        app: todo-mongo
    spec:
      containers:
      - name: todo-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: mongodb_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: mongodb_password
        volumeMounts:
        - name: todo-mongo-vol
          mountPath: /data/db
      volumes:
      - name: todo-mongo-vol
        persistentVolumeClaim:
          claimName: todo-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: todo-mongo-service
spec:
  selector:
    app: todo-mongo
  ports:
  - port: 27017
