apiVersion: v1
kind: PersistentVolume

metadata:
  name: todo-pv

spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

  storageClassName: standard

  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /todo-data/
    type: DirectoryOrCreate
