apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: todo-pvc

spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem

  volumeName: todo-pv
  resources:
    requests:
      storage: 500Mi

  storageClassName: standard
