apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.todoBackend.service.name}}
spec:
  selector:
    app:  {{ .Values.todoBackend.name}}
  type:  {{.Values.todoBackend.service.type}}
  ports:
  {{- range .Values.todoBackend.service.ports }}
  - protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end}}