apiVersion: apps/v1
kind: Deployment
{{ $fullname := include "eks.fullname" . }}
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    namespace: {{ .Release.Namespace }}
    chart: {{ include "eks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $fullname }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ $fullname }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- range .Values.image.ports }}
        - containerPort: {{ .containerPort | int }}
          protocol: {{ .protocol }}
          name: {{ .name }}
        {{- end }}
