apiVersion: v1
kind: Service
{{ $appName := include "eks.fullname" . }}
{{ $serviceName := printf "%s-service" $appName }}

metadata:
  name: {{ $serviceName }}
spec:
  selector:
    app:  {{ $appName }}
  type:  {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - protocol: {{ .protocol }}
    name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end}}