apiVersion: apps/v1
kind: Deployment

metadata:
    name: {{ .Chart.Name}}
    labels:
        app: {{ .Chart.Name}}
        release: {{ .Release.Name}}
        chart: {{ .Chart.Name}}-{{ .Chart.Version}}
        heritage: {{ .Release.Service}}

spec:
  replicas: {{default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app:  {{ .Chart.Name }}
        release: {{ .Release.Name }}
    
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- range .Values.ports}}
        - containerPort: {{ .containerPort }}
          protocol: {{ .protocol }}
        {{- end}}
