apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-service
  labels:
    app: {{ .Chart.Name}}
    release: {{ .Release.Name}}
    chart: {{ .Chart.Name}}-{{ .Chart.Version}}
    heritage: {{ .Release.Service}}

spec:
  selector:
    app: {{ .Chart.Name}}
  type: {{ .Values.service.type}}
  ports:
  {{- range .Values.service.ports}}
  - protocol: {{ .protocol}}
    port: {{ .port}}
    targetPort: {{ .targetPort}}
  {{- end}}