name: kubernetes-todo
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - todo_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
    volumes:
      - mongo_data:/data/db

  todo_backend:
    image: avvkavvk/todo_backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: todo_backend
    ports:
      - "5000:5000"
    networks:
      - todo_network
    environment:
      - PORT=5000
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=secretpassword
    depends_on:
      - mongo
  todo_frontend:
    image: avvkavvk/todo_frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: todo_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_API_URL=http://localhost:5000/todos
    networks:
      - todo_network
    depends_on:
      - todo_backend

volumes:
  mongo_data:

networks:
  todo_network:
    driver: bridge
